name: Generate and deploy Service-Public.fr data

on:
  schedule:
    - cron:  '0 10 * * 2'
  push:
    branches-ignore:
      - 'gh-pages'
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.12]

    steps:
    - uses: actions/checkout@v2
    - name: Setup python version
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install xsv
      run: |
        wget --quiet https://github.com/jqnatividad/qsv/releases/download/0.119.0/qsv-0.119.0-i686-unknown-linux-gnu.zip
        unzip qsv-0.119.0-i686-unknown-linux-gnu.zip
        pwd >> $GITHUB_PATH        
    - name: Download data
      run: |
        wget --quiet https://www.data.gouv.fr/fr/datasets/r/73302880-e4df-4d4c-8676-1a61bb997f3d
    - name: Extract data
      run: |
        tar -xvf 73302880-e4df-4d4c-8676-1a61bb997f3d --wildcards '*.json' -O > services-publics.json
        tar -tvf 73302880-e4df-4d4c-8676-1a61bb997f3d | tail -c39 > metadata.txt
    - name: Transform data
      run: |
        mkdir output
        python3 transform_dataset.py
    - name: Focus
      run: |
        qsv join id focus.csv id output/services_publics.csv |qsv select categorie,official_name,branch,name,contact:phone,contact:website,contact:email,ref:FR:SIRET,longitude,latitude,address_txt,opening_hours,insee,id,osm_id > output/focus_with_osm.csv
    - name: Pole Emploi
      run: |
        cat output/services_publics.csv |qsv search -s categorie '^france_travail' | qsv select categorie,official_name,longitude,latitude,address_txt,opening_hours,insee,id > output/france_travail.csv        
    - name: Check diff
      id: check
      run: |
        wget https://raw.githubusercontent.com/nlehuby/sepuqu/refs/heads/gh-pages/focus_with_osm.csv -O old_focus_with_osm.csv
        diff old_focus_with_osm.csv output/focus_with_osm.csv > diff_focus_output.txt || echo "Diff"
        if [ -s diff_focus_output.txt ]; then
          echo "files_different=true" >> "$GITHUB_OUTPUT"
        else
          echo "files_different=false" >> "$GITHUB_OUTPUT"
        fi
    - name: Alert if diff
      if: ${{ steps.check.outputs.files_different == 'true' }}
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DIFFED_FILE: focus
        steps.check.outputs.files_different: ${{ steps.check.outputs.files_different }}
      with:
        filename: .github/alert_template.md
    - name: Deploy
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: output
